# Generated by Django 5.2.7 on 2025-11-01 22:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuxRelayInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=255)),
                ('alternative_mat', models.CharField(blank=True, max_length=255, null=True)),
                ('mat_group', models.CharField(blank=True, max_length=255, null=True)),
                ('basic_data_text', models.TextField(blank=True, null=True)),
                ('material_description', models.TextField(blank=True, null=True)),
                ('standard_price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_stock', models.IntegerField(default=0)),
                ('per', models.CharField(blank=True, max_length=50, null=True)),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inventory', to=settings.AUTH_USER_MODEL)),
                ('last_updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inventory', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
